---
name: Tests AMD64
permissions: read-all
on: [push, pull_request]
jobs:
  test-linux-amd64:
    uses: ./.github/workflows/tests-template.yml
  test-linux-amd64-race:
    uses: ./.github/workflows/tests-template.yml
    with:
      runs-on: ubuntu-latest
      targets: "['linux-unit-test-4-cpu-race']"

  coverage:
    needs:
      - test-linux-amd64
      - test-linux-amd64-race
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - id: goversion
        run: echo "goversion=$(cat .go-version)" >> "$GITHUB_OUTPUT"
      - uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v5.1.0
        with:
          go-version: ${{ steps.goversion.outputs.goversion }}
      - run: make coverage
